### PR TITLE
Inherit stderr when running `cargo doc` to print progress

### PR DESCRIPTION
**Pull request by Enselic**
Currently, when running `cargo api` on a big crate, there is no output for a
long time, since `cargo doc` runs silently. This is confusing. The tool seems broken/stuck.

Instead, inherit stderr to print the progress of running `cargo doc`. We don't want to
inherit stdout since it should be easy to pipe the output of `cargo api` to a
file without progress noise. Luckily, `cargo` prints progress to stderr.

# Example usage

```
% cd fixtures/macros/new
% ../../../target/debug/cargo-api api --format md
 Documenting macros_new v1.0.0 (/Users/jobb/src/cargo-api/fixtures/macros/new)
    Finished dev [unoptimized + debuginfo] target(s) in 1.10s
# `macros_new`

**`macros_new::Item`** *(Struct)*

**`macros_new::abc`** *(Function)*

**`macros_new::bar`** *(Macro)*

**`macros_new::quux2`** *(Macro)*
```

Piping still works as one would expect:

```
% ../../../target/debug/cargo-api api --format md > /tmp/out
 Documenting macros_new v1.0.0 (/Users/jobb/src/cargo-api/fixtures/macros/new)
    Finished dev [unoptimized + debuginfo] target(s) in 1.07s
% cat /tmp/out 
# `macros_new`

**`macros_new::Item`** *(Struct)*

**`macros_new::abc`** *(Function)*

**`macros_new::bar`** *(Macro)*

**`macros_new::quux2`** *(Macro)*
```

### CODE REVIEW

**Comment by epage** [comment]
This works for  `cargo api` but its also meant to be used as a library and I always feel dirty doing IO in a library.  One alternative is we add our own messages before/after.  It won't give us any progress messages though unless we make the API a lot more complicated.

Thoughts?

**Comment by scrabsha** [comment]
Another approach would be to create an additional `with_progress_callback` which takes an additional closure called with relevant information each time a new crate is documented.

This is purely hypothetical. I don't know how complex the implementation would be

**Comment by epage** [comment]
> Another approach would be to create an additional `with_progress_callback` which takes an additional closure called with relevant information each time a new crate is documented.
> 
> This is purely hypothetical. I don't know how complex the implementation would be

Yup!  That is what I was thinking of with

>  It won't give us any progress messages though unless we make the API a lot more complicated.

Maybe I oversold the complication though.

**Comment by epage** [comment]
Another option is we expose builder functions for controlling the output.  I'm leaning towards that for now.  Going ahead and merging.

**Pull request merged**
